language: ruby

rvm:
  - 1.9.3
  - 2.0.0

env:
  - FS_RAILS_VERSION=3.2
  - FS_RAILS_VERSION=4.0.0

script: 
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake travis

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4
      env: FS_RAILS_VERSION=3.2
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.2
      env: FS_RAILS_VERSION=4.0.0
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4
      env: FS_RAILS_VERSION=3.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.2
      env: FS_RAILS_VERSION=4.0.0
